loki:
  image: grafana/loki:2.9.0
  container_name: loki
  ports:
    - "3100:3100"
  volumes:
    - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    - ./loki/data:/loki  # Ensure Loki data is persistent
  restart: always

